server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 5GB     # 单个文件最大限制
      max-request-size: 5GB  # 总上传大小限制
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shardingupload?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: abc123
